krakjoe/pthreads

src/object.c
src/prepare.c
src/store.c

- Fix address collision in PTHREADS_ZG(resources) (8787eff)
Each time a resource created in another thread context is used, its address is added to `PTHREADS_ZG(resources)`. Until then it was never removed and since `PTHREADS_ZG(resources)` is tested on every resource destruction attempt, collisions would occur after some time (when `PTHREADS_ZG(resources)` contains a few hundred addresses) preventing unrelated resources from being destroyed and causing memory access violations.
Here is what was observed with Valgrind:
```
Thread 12:
==00:00:35:12.339 23371== Invalid read of size 8
==00:00:35:12.339 23371==    at 0x896C451: pthreads_resources_kept (resources.c:51)
==00:00:35:12.339 23371==    by 0x896809A: pthreads_prepared_resource_dtor (prepare.c:780)
==00:00:35:12.339 23371==    by …
```

Multiple fixes to shared resource handling/keeping

---

php_pthreads.c
php_pthreads.h
src/object.c
src/resources.c
tests/resource-keeping.phpt

Finally fixed the issue uncovered by working on #404, the fix was actually simple:
PTHREADS_ZG(resources) was destroyed before destroying EG(symbol_table): resources marked for keeping would be destroyed if stored in local variables inside ::run() and not destroyed in user-land before the end of the process.
This is fixed by declaring the PTHREADS_ZG(resources) hash-table as persistent and destroying it in ~~PHP_MSHUTDOWN_FUNCTION~~ ZEND_MODULE_POST_ZEND_DEACTIVATE_D  instead of in PHP_RSHUTDOWN_FUNCTION. Since PTHREADS_ZG(resources) is necessarily left empty at the end of a request, there is no memory waste.
I also added nice tests for this issue (3704fa9) and the previous one (2468f16).
Another thing I like to do is make Pthreads throw an exception if the user tries to explicitly close …

PTHREADS_ZG(resources) destroyed too early

---

tests/killed-info.phpt

Wait for the thread to finish starting before killing it else the killed thread could be signalled while in pthread_cond_broadcast() triggered by pthreads_state_set(current->state, PTHREADS_ST_RUNNING TSRMLS_CC) in src/object.c:951
Bug analysis: https://github.com/krakjoe/pthreads/issues/273#issuecomment-68620832

Fix #273 by fixing the test

---

tests/binding.phpt

`::notify()` calls were not synchronized and so in the following code:
```php
foreach($threads as $thread) {
$thread->synchronized(function() use($thread){
if (!$thread->done)
var_dump($thread->wait());
else var_dump($thread->done);
});
}
```
`$thread->done()` could be set to true just between the `if` and the `::wait()` if the treads are started faster than usual as is expected with #424.

Fix possible race condition in tests/binding.phpt as seen in #424

---

src/copy.h
tests/static-variables.phpt

An attempt at fixing #391 for PHP versions 5.x.
As per the pthreads 2.0.x docs, resources and objects should be nullified inside static variables, so now `pthreads_copy_statics()` skips over those types of values when copying lexical statics by simple type checking. The entry for the variable will instead be empty, which will return a fresh `NULL` after copy to a child thread. Normal zvals are copied and their refcounts incremented.

Fix #391 for PHP 5.x

---

php_pthreads.c

Hey,
as discussed in issue #557 here is the pull request to add the open source project Homegear to your SAPI whitelist :wink:. You can find the source code here: https://github.com/Homegear/Homegear. The source code for the script engine can be found in the subdirectory src/ScriptEngine. The script engine itself runs in a seperate process for stability reasons (class ScriptEngineClient), which communicates with the main process (class ScriptEngineServer). The SAPI implementation is in php_sapi.cpp. The function reference is on https://ref.homegear.eu/php.html (only the PHP reference is complete - I'm currently working on the other parts). You can find an example PHP script using pthreads on https://github.com/Homegear/Homegear-OpenWeatherMap/blob/master/OpenWeatherMap.xml or in the …

Added Homegear to SAPI whitelist

---

tests/pools.phpt

The variable protected is incorrect and the correct logger variable is created as public.

Fix pool test

---

src/store.c

Cleanup on synchronized or reading a property is inconsistent, therefore cleanup should also happen on writing a property. Moreover the cleanup behavior on synchronized is misleading. 
```
class myRec extends Threaded {
public $data1;
public $data2;
}
class storage extends Threaded {
private $store = array();
public function addRecord($key,$data) {
$this->store->synchronized(function () use ($key, $data)
{
$this->store[$key] = $data;
});
}
public function delAll() {
$this->store->synchronized(function ()
{
foreach($this->store as $key => $data)
{
unset($this->store[$key]);
}
});
}
public function countRecs() {
return count($this->store);
}
}
class myThread extends Thread
{
private static $type;
public function __construct($type,$storage)
{
self::$type = $type;
$this->storage = $storage;
} …
```

fix #580 #681

---

appveyor.yml
src/pthreads.h
src/socket.c

`AF_UNIX` is defined in `WinSock2.h` which is included by `php_network.h`, meaning `AF_UNIX` is never _not_ defined. However, Windows doesn't support Unix domain sockets.
This fixes #713 .

fix compile with Visual Studio on windows

---

src/prepare.c
tests/anon-bound-inherited.phpt
tests/anon-unbound-inherited.phpt

The old class entry copying logic was a mess. This PR refactors this so that the new class copying logic is cleaner, simpler, and faster.
Broadly, the following changes have been made:
- Removal of the unused `thread` parameter to `pthreads_prepared_entry_static_members`
- Removal of the conditional copying of static class members, since they are always copied later by `pthreads_prepare_classes`
- Shift around the copying logic with respect to unbound anonymous classes. Previously, the copying logic would sometimes be executed twice when copying the following ce information:
- `function_table`
- magic methods
- `properties_info`
- `default_properties_table`
- `constants_table`
Whilst the double copying was not a problem in many cases, it did cause unnecessary overhead (though this would …

Refactor class preparation logic

---

src/prepare.c
src/prepare.h
src/pthreads.h

I have no further details or tests for this bug fix, sorry.

fix static property circular references during class preparation

---

src/globals.c

wrong version check, `GC_ADDREF` only exists in 7.3-dev. If I read correctly, https://github.com/krakjoe/pthreads/commit/edf81d3cc0f34c1fcb3f8f14435a9a122f6e482f was actually intended to fix 7.3, not 7.2.

fix compile error on 7.2

---

src/object.c
src/prepare.c
src/prepare.h
tests/anon-interceptors.phpt

I've splitted up the functions ```pthreads_prepared_entry_static_members``` and ```pthreads_complete_entry``` to smaller ones. New (partially prepared) classes will get inserted into the ```EG(class_table)``` HT and not into the ```resolve``` HT anymore. I'm quite not happy with the wording of function ```pthreads_prepared_entry_late_bindings```, suggestions are welcome. Your opinions, of course, too.

class preparation revision

---

examples/stub.php
src/thread.h

This constant does not exist in pthreads v3 as of 3.1.7.

Remove remnants of PTHREADS_ALLOW_GLOBALS

---

src/socket.c
tests/socket-construct.phpt

This includes a fix for #798 , a test for it, and a fix for another Windows-specific bug that broke the test.
- Socket::__construct() now works correctly on Windows.
- Socket::close() no longer raises exceptions on Windows.
These are Windows-specific issues, but the fixes have been tested on unix as well nonetheless.

Windows socket fixes

---

appveyor.yml

Prior to this, AppVeyor builds would still be marked as "succeeded" even if tests failed.

Fail AppVeyor build if any tests fail

---

examples/NonBlockingSocketServer.php
src/socket.c

In non blocking state Socket::accept() returns false instead of throwing an exception to match the behavior of socket_accept(). Also added an example.

Fixes #733: accept() recognizes socket blocking state

---

tests/socket-sentto-recvfrom-ipv4-udp-win32.phpt

Windows adds newlines at the end of most socket error messages.
see https://ci.appveyor.com/project/krakjoe/pthreads/build/master.274/job/lwjo6yv8mi5vb79v#L743

tiny fix for win32 IPv4 test

---

src/store.c
tests/volatile-nested.phpt

@tpunt @krakjoe Volatile objects are not suitable for nested and/or complex structures, because of the missing refcount. I hope the contained test clarifies the use case of this PR.

Ability to nest volatile objects

---

classes/socket.h
examples/stub.php
src/socket.c
src/socket.h
tests/socket-connect-params-af-inet.phpt
tests/socket-connect-params-af-unix.phpt

- Parameter `port` can be optional on AF_UNIX sockets
- Added some tests

Rework of Socket::connect

---

examples/stub.php

This updates the stub to match pthreads v3 properly, as per the arginfo of the extension. Some issues were discovered in the process (see #835 and #836), so method signatures have been adjusted to match the documentation where there are mismatches.
The formatting in this file is very inconsistent, I went to great pains to avoid reformatting it to avoid polluting the diff. If it's desirable to have a reformat in this PR, let me know, but please don't squash-merge. :)

Fixed some issues with stub method signatures

---

classes/socket.h
examples/stub.php
src/socket.c
src/socket.h

Added missing method Socket::strerror(int $error):?string equal to php-src sockets API

New static method Socket::strerror()

---

classes/socket.h
examples/stub.php
php_pthreads.c
src/socket.c
src/socket.h
tests/socket-ipv4loop.phpt
tests/socket-ipv6loop.phpt
tests/socket-read-type.phpt
tests/socket-unixloop.phpt

This PR adds `$type` to Socket::read() and the both constants `Socket::PHP_NORMAL_READ` as well as `Socket::PHP_BINARY_READ` to mimic php-src Sockets API. Four more tests were added.

706 - Socket::read() adds Socket::PHP_NORMAL_READ and Socket::PHP_BINARY_READ

---

appveyor.yml

```
Fatal error: Uncaught SDK\Exception: Failed to fetch supported branches in C:\projects\php-sdk\lib\php\libsdk\SDK\Config.php:155
Stack trace:
#0 C:\projects\php-sdk\lib\php\libsdk\SDK\Config.php(165): SDK\Config::getKnownBranches()
#1 C:\projects\php-sdk\bin\phpsdk_deps.php(99): SDK\Config::setCurrentBranchName('7.2')
#2 {main}
thrown in C:\projects\php-sdk\lib\php\libsdk\SDK\Config.php on line 155
Command exited with code 255
```
Newer SDK fixes this issue (I hit the same bug on my own projects this morning).

Fix AppVeyor crashing during build

---

src/monitor.c

This bug occurs due to implementation differences in pthread-w32 vs other platforms. In glibc, [`pthread_mutexattr_destroy` is a no-op]( https://code.woboq.org/userspace/glibc/nptl/pthread_mutexattr_destroy.c.html#__pthread_mutexattr_destroy), so not calling it did no harm, but in pthread-w32 it [actually does something important](https://github.com/GerHobbelt/pthread-win32/blob/master/pthread_mutexattr_destroy.c#L47), i.e. freeing memory.
This bug was discovered using Visual Studio memory profiler. It may affect other platforms depending on the libc in use.
I haven't written tests for this because observing it from an automated standpoint to watch for leaks is tedious and takes a long time. However, this fix has been tested manually with the test script in #822 and is confirmed to fix …

Fixed leaking pthread_mutexattr_t on Windows, closes #822

---

classes/threaded.h
tests/runtime-inheritance-volatile.phpt

`Threaded` objects are often poorly suited for runtime class extension because of their immutability characteristics. Classes which are not `Threaded` need to be adapted to extend `Threaded` (for example, overwriting a coerced array on a runtime-extended class crashes).
Because `Volatile` descends from `Threaded`, `Volatile::extend()` exists, but does not work as might be expected - it behaves exactly the same as `Threaded::extend()`.
This PR changes `Threaded::extend()` to apply the scope it was called from, instead of always applying the `Threaded` parent.
A possible alternative to this could be to simply move `extend()` to `Volatile` completely, since as I said above `Threaded` isn't suited to code that doesn't know it's `Threaded` anymore due to immutability.

Allow Volatile::extend() to work as expected

---

src/socket.c

VS2017 code analysis complains about "Using uninitialized memory 'retval'". While these cases should theoretically never get hit, they shouldn't be returning uninitialized variables anyway.

Guard against returning uninitialized variables in switch-cases

---

src/prepare.c
src/store.c
src/store.h
src/thread.h

This fixes #753 .
See https://github.com/krakjoe/pthreads/pull/861#issuecomment-412031461 for long explanation - the TL;DR is that serialization can cause objects to be modified on the child thread, which will cause problems.
The solution here is to serialize it in `pthreads_prepare_parent()` and then unserialize during the thread's prepared startup. A similar solution will likely be needed for statics.

Fixed unsafe copying of exception handler

---

classes/socket.h
php_pthreads.c
src/socket.c
src/socket.h
tests/socket-shutdown.phpt

@SirSnyder this one's for you - some suggested alterations of my own for #845

Improvements & fixes for Socket::shutdown() PR
